### ISSUE TITLE
EPIC improve designs

### ISSUE THREAD

**Issue by ditkin** [ditkin/magicui#22]
<details>
<summary>View current designs</summary>

## Room selection screen
![image](https://user-images.githubusercontent.com/5571242/66878621-b30bda80-ef88-11e9-8737-602f48d8e125.png)

## One player
![image](https://user-images.githubusercontent.com/5571242/66878629-c6b74100-ef88-11e9-9e07-240d92f82387.png)

## Two players
![image](https://user-images.githubusercontent.com/5571242/66878634-cf0f7c00-ef88-11e9-909c-6311365c8b31.png)
</details>

## Goal

- [ ] Add page header to game view
- [ ] Add page header to rooms view
- [ ] Design better room picker
- [ ] Design better room maker
